In [30]:
import pandas as pd

In [31]:
df=pd.read_csv('/content/bank-full.csv')

In [32]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [33]:
df.shape

(45211, 17)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [35]:
df.describe(include='all')

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
count,45211.000000,45211,45211,45211,45211,45211.000000,45211,45211,45211,45211.000000,45211,45211.000000,45211.000000,45211.000000,45211.000000,45211,45211
unique,NaN,12,3,4,2,NaN,2,2,3,NaN,12,NaN,NaN,NaN,NaN,4,2
top,NaN,blue-collar,married,secondary,no,NaN,yes,no,cellular,NaN,may,NaN,NaN,NaN,NaN,unknown,no
freq,NaN,9732,27214,23202,44396,NaN,25130,37967,29285,NaN,13766,NaN,NaN,NaN,NaN,36959,39922
mean,40.936210,NaN,NaN,NaN,NaN,1362.272058,NaN,NaN,NaN,15.806419,NaN,258.163080,2.763841,40.197828,0.580323,NaN,NaN
std,10.618762,NaN,NaN,NaN,NaN,3044.765829,NaN,NaN,NaN,8.322476,NaN,257.527812,3.098021,100.128746,2.303441,NaN,NaN
min,18.000000,NaN,NaN,NaN,NaN,-8019.000000,NaN,NaN,NaN,1.000000,NaN,0.000000,1.000000,-1.000000,0.000000,NaN,NaN
25%,33.000000,NaN,NaN,NaN,NaN,72.000000,NaN,NaN,NaN,8.000000,NaN,103.000000,1.000000,-1.000000,0.000000,NaN,NaN
50%,39.000000,NaN,NaN,NaN,NaN,448.000000,NaN,NaN,NaN,16.000000,NaN,180.000000,2.000000,-1.000000,0.000000,NaN,NaN
75%,48.000000,NaN,NaN,NaN,NaN,1428.000000,NaN,NaN,NaN,21.000000,NaN,319.000000,3.000000,-1.000000,0.000000,NaN,NaN
max,95.000000,NaN,NaN,NaN,NaN,102127.000000,NaN,NaN,NaN,31.000000,NaN,4918.000000,63.000000,871.000000,275.000000,NaN,NaN

In [36]:
df.head(2)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no

In [37]:
df=df.drop(['contact','poutcome'],axis=1)

In [38]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['job'] = le.fit_transform(df['job'])
df['marital']=le.fit_transform(df['marital'])
df['education']=le.fit_transform(df['education'])
df['housing']=le.fit_transform(df['housing'])
df['loan']=le.fit_transform(df['loan'])
df['month']=le.fit_transform(df['month'])
df['default']=le.fit_transform(df['default'])
df.head()

,age,job,marital,education,default,balance,housing,loan,day,month,duration,campaign,pdays,previous,y
0,58,4,1,2,0,2143,1,0,5,8,261,1,-1,0,no
1,44,9,2,1,0,29,1,0,5,8,151,1,-1,0,no
2,33,2,1,1,0,2,1,1,5,8,76,1,-1,0,no
3,47,1,1,3,0,1506,1,0,5,8,92,1,-1,0,no
4,33,11,2,3,0,1,0,0,5,8,198,1,-1,0,no

In [39]:
from sklearn import tree
from sklearn.model_selection import train_test_split

In [40]:
X = df.drop('y', axis=1)
y = df['y']

In [42]:
X

,age,job,marital,education,default,balance,housing,loan,day,month,duration,campaign,pdays,previous
0,58,4,1,2,0,2143,1,0,5,8,261,1,-1,0
1,44,9,2,1,0,29,1,0,5,8,151,1,-1,0
2,33,2,1,1,0,2,1,1,5,8,76,1,-1,0
3,47,1,1,3,0,1506,1,0,5,8,92,1,-1,0
4,33,11,2,3,0,1,0,0,5,8,198,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,17,9,977,3,-1,0
45207,71,5,0,0,0,1729,0,0,17,9,456,2,-1,0
45208,72,5,1,1,0,5715,0,0,17,9,1127,5,184,3
45209,57,1,1,1,0,668,0,0,17,9,508,4,-1,0
45210,37,2,1,1,0,2971,0,0,17,9,361,2,188,11

In [43]:
y

0         no
1         no
2         no
3         no
4         no
        ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: y, Length: 45211, dtype: object

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [45]:
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [46]:
print(f"Accuracy on test set: {model.score(X_test, y_test)}")

Accuracy on test set: 0.8635408603339599

In [54]:
print(model.feature_names_in_)
print(new_data.columns)

['age' 'job' 'marital' 'education' 'default' 'balance' 'housing' 'loan'
 'day' 'month' 'duration' 'campaign' 'pdays' 'previous']
Index(['age', 'job', 'marital', 'duration', 'balance', 'education', 'housing',
       'loan', 'day', 'month', 'default', 'campaign', 'pdays', 'previous'],
      dtype='object')

In [55]:
new_data = pd.DataFrame({
    'age':[34,50,80,60,20],
    'job': ['management', 'blue-collar', 'technician', 'admin.', 'services'],
    'marital': ['married', 'single', 'married', 'single', 'married'],
    'education': ['university.degree', 'high.school', 'professional.course', 'university.degree', 'high.school'],
    'default': ['no', 'yes', 'no', 'no', 'yes'],
    'balance':[5626,32632,3265,4859,4157],
    'housing': ['no', 'yes', 'no', 'no', 'yes'],
    'loan': ['no', 'yes', 'no', 'yes', 'no'],
    'day':['mon','tue','tue','mon','fri'],
    'month': ['may', 'apr', 'jun', 'feb', 'aug'],
    'duration':[84,264,336,62,45],
    'campaign':[1,1,1,1,1],
    'pdays':[-1,-1,-1,-1,-1],
    'previous':[0,0,0,0,0]
})

new_data['job'] = le.fit_transform(new_data['job'])
new_data['marital'] = le.fit_transform(new_data['marital'])
new_data['education'] = le.fit_transform(new_data['education'])
new_data['housing'] = le.fit_transform(new_data['housing'])
new_data['loan'] = le.fit_transform(new_data['loan'])
new_data['month'] = le.fit_transform(new_data['month'])
new_data['default'] = le.fit_transform(new_data['default'])
new_data['age'] = le.fit_transform(new_data['age'])
new_data['day'] = le.fit_transform(new_data['day'])
new_data['campaign'] = le.fit_transform(new_data['campaign'])
new_data['pdays'] = le.fit_transform(new_data['pdays'])
new_data['duration'] = le.fit_transform(new_data['duration'])
new_data['balance'] = le.fit_transform(new_data['balance'])
predictions = model.predict(new_data)

print(predictions)

['no' 'no' 'no' 'no' 'yes']